### ISSUE TITLE
Build failing due to old SPIRV-Headers DEPS revision

### ISSUE THREAD

**Issue by sarahM0** [KhronosGroup/SPIRV-Tools#4364]
While rolling vulkan-deps, spirv-tools is hitting an error:
```
../../third_party/vulkan-deps/spirv-tools/src/source/val/validate_extensions.cpp:3115:12: error: use of undeclared identifier 'OpenCLDebugInfo100DebugModuleINTEL'
case OpenCLDebugInfo100DebugModuleINTEL:
```

This enum value is added this PR: https://github.com/KhronosGroup/SPIRV-Headers/pull/224
which is merged after current version of the spirv-headers:

https://github.com/KhronosGroup/SPIRV-Tools/blob/e065c482c6c98ef22900822d32a21df8c5473054/DEPS#L9

**Comment by alan-baker** [comment]
Believe this was fixed by #4369

**Comment by ArthurSonzogni** [comment]
Still failing at revision #4369

```
../../third_party/vulkan-deps/spirv-tools/src/source/val/validate_extensions.cpp:3115:12: error: use of undeclared identifier 'OpenCLDebugInfo100DebugModuleINTEL'
      case OpenCLDebugInfo100DebugModuleINTEL:
           ^
1 error generated.
```

Could you please re-open this bug?

**Comment by ArthurSonzogni** [comment]
+CC @pkasting
